### ISSUE TITLE
Ignored cooperation offer / 无视合作提议

### ISSUE THREAD

**Issue by truthfulphoenix** [Guo12181/Guo12181.github.io#1]
We, Future Gadget Team (https://futuregadget.team), sent you a total of two cooperation requests (one to Guo12181@126.com, and another one to FGLChina@outlook.com, both sent from truthfulphoenix@futuregadget.team), but our letters seem to have been ignored. We would like to know if you would care to cooperate with our branch of Future Gadget Laboratory. 

Sincerely,

truthfulphoenix

El Psy Congroo

-----------------------------------

我们，未来的小工具团队（https://futuregadget.team），总共向你们发出了两个合作请求（一个给 Guo12181@126.com，另一个给 FGLChina@outlook.com，都是从truthfulphoenix@futuregadget.team），但我们的信似乎被忽略了。我们想知道你是否愿意与我们的 "未来小工具实验室 "分部合作。

真诚的、

truthfulphoenix

El Psy Congroo

**Comment by Guo12181** [comment]
*Translated from bing*
---
We have received it, we are sorry that we did not check the email recently, and will reply as soon as possible.
---
我们已经收到，十分抱歉近日没有查看邮件，将会尽快给出答复。
---
Мы получили его, мы сожалеем, что недавно не проверили электронную почту, и ответим как можно скорее.
---
